
project_id = "kjjnnzwtqniqmaupecle"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[functions]
[functions.send-welcome-email]
verify_jwt = false
